
---
language: node_js
node_js:
- '5'
- '6'
install: true
env:
- TEST=.
- TYPECHECK=.
script:
- |
    if [ $TEST ]; then
      cd $TEST && npm install && npm run jest -- --runInBand --no-watchman
    fi
- |
    if [ $TYPECHECK ]; then
      cd $TYPECHECK && npm install && npm run typecheck
    fi
